name: CI

on:
  push:
    branches:
      - main

jobs:
  login:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    environment: production
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Login to SCW
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/home-kid-management
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          entrypoint: ./backend/Dockerfile
          push: false
          tags: backend:latest
