name: CI-backend

on:
  push:
    paths:
      - "backend/**"
    tags:
      - "@hkm/back@*"
    branches:
      - main

jobs:
  deploy-staging:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/@hkm') }}
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Login to SCW
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/home-kid-management
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            APP_KEYS=${{ secrets.APP_KEYS }}
            API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
            ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
            TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_SSL=${{ secrets.DATABASE_SSL }}
            SCALEWAY_ACCESS_KEY_ID=${{ secrets.SCW_ACCESS_KEY }}
            SCALEWAY_ACCESS_SECRET=${{ secrets.SCW_SECRET_KEY }}
            SCALEWAY_REGION=${{ secrets.SCALEWAY_REGION }}
            SCALEWAY_ENDPOINT=${{ secrets.SCALEWAY_ENDPOINT }}
            SCALEWAY_BUCKET=${{ secrets.SCALEWAY_BUCKET }}
          context: ./backend
          push: true
          tags: rg.fr-par.scw.cloud/home-kid-management/backend-staging:latest
      - uses: ./.github/workflows/deploy-container.yml
        with:
          CONTAINER_ID: c9604ec2-a4c9-43ed-95c5-4bf220029531
          REGISTRY_IMAGE: rg.fr-par.scw.cloud/home-kid-management/backend-staging:latest

  deploy-production:
    defaults:
      run:
        working-directory: ./backend
    if: startsWith(github.ref, 'refs/tags/@hkm')
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Login to SCW
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/home-kid-management
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set version env variable
        run: |
          echo "APP_VERSION=$(echo ${{ github.ref_name }} | cut -d "@" -f 3)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            APP_KEYS=${{ secrets.APP_KEYS }}
            API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
            ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
            TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_SSL=${{ secrets.DATABASE_SSL }}
            SCALEWAY_ACCESS_KEY_ID=${{ secrets.SCW_ACCESS_KEY }}
            SCALEWAY_ACCESS_SECRET=${{ secrets.SCW_SECRET_KEY }}
            SCALEWAY_REGION=${{ secrets.SCALEWAY_REGION }}
            SCALEWAY_ENDPOINT=${{ secrets.SCALEWAY_ENDPOINT }}
            SCALEWAY_BUCKET=${{ secrets.SCALEWAY_BUCKET }}
          context: ./backend
          push: true
          tags: |
            rg.fr-par.scw.cloud/home-kid-management/backend-production:latest
            rg.fr-par.scw.cloud/home-kid-management/backend-production:${{ env.APP_VERSION }}
      - uses: ./.github/workflows/deploy-container.yml
        with:
          CONTAINER_ID: 7fbe6229-8c75-40c2-adec-8b7c614e9625
          REGISTRY_IMAGE: rg.fr-par.scw.cloud/home-kid-management/backend-production:latest
