name: CI
on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: "https://backendhomekidmanage2go4qzln-container-kid-home-management.functions.fnc.fr-par.scw.cloud/"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - name: build
        run: |
          bun install --frozen-lockfile
          bun run build
      - uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: ./dist

  deploy-staging:
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    environment: staging
    runs-on: ubuntu-latest
    needs: [build]
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_BUCKET_NAME: "home-kid-management-staging"
      SCW_END_POINT: "https://s3.fr-par.scw.cloud/"
      DIST_FOLDER_TO_DEPLOY: "./app-dist"
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: ${{ env.SCW_END_POINT }}
          aws_key_id: ${{ env.SCW_ACCESS_KEY }}
          aws_secret_access_key: ${{ env.SCW_SECRET_KEY }}
          aws_bucket: ${{ env.SCW_BUCKET_NAME }}
          source_dir: ${{ env.DIST_FOLDER_TO_DEPLOY }}
          destination_dir: ''

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production
    runs-on: ubuntu-latest
    needs: [build]
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_BUCKET_NAME: "home-kid-management"
      SCW_END_POINT: "https://s3.fr-par.scw.cloud/"
      DIST_FOLDER_TO_DEPLOY: "./app-dist"
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: ${{ env.SCW_END_POINT }}
          aws_key_id: ${{ env.SCW_ACCESS_KEY }}
          aws_secret_access_key: ${{ env.SCW_SECRET_KEY }}
          aws_bucket: ${{ env.SCW_BUCKET_NAME }}
          source_dir: ${{ env.DIST_FOLDER_TO_DEPLOY }}
          destination_dir: ''