name: Release
on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
jobs:
  release:
    defaults:
      run:
        working-directory: ./frontend
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: oven-sh/setup-bun@v2
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - run: bun install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release"
          title: "chore: release"
          publish: bun release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
