name: CI-frontend
on:
  push:
    paths:
      - "frontend/**"
    tags:
      - "@hkm/front@*"
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: "https://backendhomekidmanage2go4qzln-container-hkm-staging.functions.fnc.fr-par.scw.cloud/"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-use-and-cache
      - name: Set VITE_BACKEND_URL if it is production release
        if: startsWith(github.ref, 'refs/tags/@hkm')
        run: echo "VITE_BACKEND_URL=https://backendhomekidmanage2go4qzln-container-kid-home-management.functions.fnc.fr-par.scw.cloud/" >> $GITHUB_ENV
      - name: build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: ./frontend/dist # path used for actions need to be root relative

  deploy-staging:
    defaults:
      run:
        working-directory: ./frontend
    if: ${{ ! startsWith(github.ref, 'refs/tags/@hkm') }}
    environment: staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: https://s3.fr-par.scw.cloud/
          aws_key_id: ${{ secrets.SCW_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SCW_SECRET_KEY }}
          aws_bucket: home-kid-management-staging
          source_dir: ./app-dist # dist folder to deploy, path used for actions need to be root relative
          destination_dir: ""

  deploy-production:
    defaults:
      run:
        working-directory: ./frontend
    if: startsWith(github.ref, 'refs/tags/@hkm')
    environment: production
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - uses: shallwefootball/s3-upload-action@master
        with:
          endpoint: https://s3.fr-par.scw.cloud/
          aws_key_id: ${{ secrets.SCW_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SCW_SECRET_KEY }}
          aws_bucket: home-kid-management
          source_dir: "./app-dist" # dist folder to deploy, path used for actions need to be root relative
          destination_dir: ""
