name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      # - name: Git Identity
      #   run: |
      #     git config --global user.name 'Scaleway Bot'
      #     git config --global user.email 'github@scaleway.com'
      #     git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      - run: bun install
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release"
          title: "chore: release"
          version: bun version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
