name: Release
on:
  push:
    branches:
      - feat/auto-deploy
# on:
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string
jobs:
  release:
    name: Test scaleway cli
    runs-on: ubuntu-latest
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_ORGANIZATION_ID: fbb62ce1-1ee8-4d84-9730-02e89ce5958f
      SCW_DEFAULT_PROJECT_ID: fbb62ce1-1ee8-4d84-9730-02e89ce5958f
      SCW_DEFAULT_REGION: fr-par
      SCW_DEFAULT_ZONE: fr-par-1
      CONTAINER_ID: c9604ec2-a4c9-43ed-95c5-4bf220029531
      REGISTRY_IMAGE: rg.fr-par.scw.cloud/home-kid-management/backend-staging:latest
    steps:
      - name: Install Scaleway CLI
        run: |
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
      - name: Test Scaleway CLI
        run: |
          scw container container update ${CONTAINER_ID} registry-image=${REGISTRY_IMAGE}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build for environment
#         run: |
#           echo "Building for ${{ inputs.environment }}"
#           ./build.sh --env ${{ inputs.environment }}
