name: CI-test

on:
  push:
    paths:
      - "test/**"
    tags:
      - "*"
    branches:
      - main

jobs:
  deploy-staging:
    defaults:
      run:
        working-directory: ./test
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/@hkm') }}
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: command
        run: echo ${{ github.ref_name }}

  deploy-production:
    defaults:
      run:
        working-directory: ./test
    if: startsWith(github.ref, 'refs/tags/@hkm')
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: command
        run: echo ${{ github.ref_name }}
