name: CI-test

on:
  push:
    branches:
      - feat/test-ci

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-container.yml
    with:
      CONTAINER_ID: c9604ec2-a4c9-43ed-95c5-4bf220029531
      REGISTRY_IMAGE: rg.fr-par.scw.cloud/home-kid-management/backend-staging:latest
